/**
 * Build-time provenance constants — AUTO-GENERATED by scripts/gen-build-info.js
 * Do not edit manually. Re-generated on each build via the 'prebuild' npm script.
 */

export const GIT_COMMIT: string = '2035e19';
export const APP_VERSION: string = '1.0.0';
